# Generated by Django 5.0.4 on 2024-04-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.CharField(default=231, max_length=100),
            preserve_default=False,
        ),
    ]
